RabbitHouse/Areas/Management/ViewModels/ProductCategoryManageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using RabbitHouse.ExternalClasses;

namespace RabbitHouse.ViewModels
{
    public class ProductCategoryManageEditViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }
        [Display(Name = "名称")]
        public string Name { get; set; }
        [Display(Name = "描述")]
        public string Description { get; set; }
        [Display(Name = "查询符号")]
        public string UrlSlug { get; set; }
    }
    public class ProductCategoryManageDetailsViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }
        [Display(Name = "名称")]
        public string Name { get; set; }
        [Display(Name = "描述")]
        public string Description { get; set; }
        [Display(Name = "查询符号")]
        public string UrlSlug { get; set; }
    }
    public class ProductCategoryManageCreateViewModel
    {
        [Display(Name = "名称")]
        public string Name { get; set; }
        [Display(Name = "描述")]
        public string Description { get; set; }
        [Display(Name = "查询符号")]
        public string UrlSlug { get; set; }
    }
    public class ProductCategoryManageDeleteViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }
        [Display(Name = "名称")]
        public string Name { get; set; }
        [Display(Name = "描述")]
        public string Description { get; set; }
        [Display(Name = "查询符号")]
        public string UrlSlug { get; set; }
    }
}

RabbitHouse/Areas/Management/Controllers/ProductCategoryManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RabbitHouse.Models;
using RabbitHouse.ViewModels;

namespace RabbitHouse.Areas.Management.Controllers
{
    public class ProductCategoryManageController : Controller
    {
        private RabbitHouseDbContext db = new RabbitHouseDbContext();

        // GET: ProductCategoryManage
        public ActionResult Index()
        {
            return View(db.ProductCategories.ToList());
        }

        // GET: ProductCategoryManage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            var vm = new ProductCategoryManageDetailsViewModel
            {
                Id=productCategory.Id,
                Name=productCategory.Name,
                Description=productCategory.Description,
                UrlSlug=productCategory.UrlSlug
            };
            return View(vm);
        }

        // GET: ProductCategoryManage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductCategoryManage/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductCategoryManageCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var productCategory = new ProductCategory
                {
                    Name = model.Name,
                    Description = model.Description,
                    UrlSlug = model.UrlSlug
                };
                db.ProductCategories.Add(productCategory);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: ProductCategoryManage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            var vm =new ProductCategoryManageEditViewModel{
                Id=productCategory.Id,
                Name=productCategory.Name,
                Description=productCategory.Description,
                UrlSlug=productCategory.UrlSlug
            };
            return View(vm);
        }

        // POST: ProductCategoryManage/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCategoryManageEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var productCategory = new ProductCategory
                {
                    Id = model.Id,
                    Name = model.Name,
                    Description = model.Description,
                    UrlSlug = model.UrlSlug
                };

                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: ProductCategoryManage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            var vm = new ProductCategoryManageDeleteViewModel
            {
                Id = productCategory.Id,
                Name = productCategory.Name,
                Description = productCategory.Description,
                UrlSlug = productCategory.UrlSlug
            };
            return View(vm);
        }

        // POST: ProductCategoryManage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {        
            var productCategory = db.ProductCategories.Find(id);

            var productsHaveTheCateogory = db.Products.Where(p => p.CategoryId == id);
            if(productsHaveTheCateogory.Count()!=0)
            {
                ModelState.AddModelError("", "在删除分类之前，请先更改或者删除拥有该分类商品的商品分类");

                var vm = new ProductCategoryManageDeleteViewModel
                {
                    Id = productCategory.Id,
                    Name = productCategory.Name,
                    Description = productCategory.Description,
                    UrlSlug = productCategory.UrlSlug
                };
                return View(vm);
            }

            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RabbitHouse/Controllers/ProductCategoryManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RabbitHouse.Models;
using RabbitHouse.ViewModels;

namespace RabbitHouse.Controllers
{
    public class ProductCategoryManageController : Controller
    {
        private RabbitHouseDbContext db = new RabbitHouseDbContext();

        // GET: ProductCategoryManage
        public ActionResult Index()
        {
            return View(db.ProductCategories.ToList());
        }

        // GET: ProductCategoryManage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            var vm = new ProductCategoryManageDetailsViewModel
            {
                Id=productCategory.Id,
                Name=productCategory.Name,
                Description=productCategory.Description,
                UrlSlug=productCategory.UrlSlug
            };
            return View(vm);
        }

        // GET: ProductCategoryManage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductCategoryManage/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductCategoryManageCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var productCategory = new ProductCategory
                {
                    Name = model.Name,
                    Description = model.Description,
                    UrlSlug = model.UrlSlug
                };
                db.ProductCategories.Add(productCategory);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: ProductCategoryManage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            var vm =new ProductCategoryManageEditViewModel{
                Id=productCategory.Id,
                Name=productCategory.Name,
                Description=productCategory.Description,
                UrlSlug=productCategory.UrlSlug
            };
            return View(vm);
        }

        // POST: ProductCategoryManage/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCategoryManageEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var productCategory = new ProductCategory
                {
                    Id = model.Id,
                    Name = model.Name,
                    Description = model.Description,
                    UrlSlug = model.UrlSlug
                };

                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: ProductCategoryManage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            var vm = new ProductCategoryManageDeleteViewModel
            {
                Id = productCategory.Id,
                Name = productCategory.Name,
                Description = productCategory.Description,
                UrlSlug = productCategory.UrlSlug
            };
            return View(vm);
        }

        // POST: ProductCategoryManage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {        
            var productCategory = db.ProductCategories.Find(id);

            var productsHaveTheCateogory = db.Products.Where(p => p.CategoryId == id);
            if(productsHaveTheCateogory.Count()!=0)
            {
                ModelState.AddModelError("", "在删除分类之前，请先更改或者删除拥有该分类商品的商品分类");

                var vm = new ProductCategoryManageDeleteViewModel
                {
                    Id = productCategory.Id,
                    Name = productCategory.Name,
                    Description = productCategory.Description,
                    UrlSlug = productCategory.UrlSlug
                };
                return View(vm);
            }

            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RabbitHouse/Areas/Management/Views/ProductCategoryManage/Create.cshtml
@model RabbitHouse.ViewModels.ProductCategoryManageCreateViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutBracket.cshtml";
}

<div class="pageheader">
    <h2><i class="fa fa-edit"></i> ProductCategoryManage<span>进行商品分类管理</span></h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","SystemManage")">首页</a></li>
            <li>商品分类</li>
            <li><a href="@Url.Action("Index","ProductCategoryManage")">商品分类列表</a></li>
            <li class="active">创建商品分类</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
    <div class="panel panel-default">
        @using (Html.BeginForm("Create", "ProductCategoryManage", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal form-bordered", enctype = "multipart/form-data" }))
        {
            <div class="panel-heading">
                <div class="panel-btns">
                    <a class="panel-close"></a>
                    <a class="minimize"></a>
                </div>
                <h4 class="panel-title">创建商品分类</h4>
                <p>您可以在此创建一个新的商品分类.</p>
            </div>

            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            <div class="panel-body panel-body-nopadding">

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                        @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <button class="btn btn-primary" type="submit">保存</button>
                    </div>
                </div>
            </div>
        }
    </div>

</div><!-- contentpanel -->

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bracket/GeneralFormScript")

    <script>
        jQuery(document).ready(function () {
            //read and show img
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#post-img').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]);

                }
            }

            $("#CoverImg").change(function (e) {
                readURL(this);
                $('#post-img-path').val(e.target.files[0].name);
            });

            "use strict";

            // Tags Input
            jQuery('#tags').tagsInput({ width: 'auto' });

            // Select2
            jQuery(".select2").select2({
                width: '100%'
            });

            // Textarea Autogrow
            jQuery('#autoResizeTA').autogrow();

            // Color Picker
            if (jQuery('#colorpicker').length > 0) {
                jQuery('#colorSelector').ColorPicker({
                    onShow: function (colpkr) {
                        jQuery(colpkr).fadeIn(500);
                        return false;
                    },
                    onHide: function (colpkr) {
                        jQuery(colpkr).fadeOut(500);
                        return false;
                    },
                    onChange: function (hsb, hex, rgb) {
                        jQuery('#colorSelector span').css('backgroundColor', '#' + hex);
                        jQuery('#colorpicker').val('#' + hex);
                    }
                });
            }

            // Color Picker Flat Mode
            jQuery('#colorpickerholder').ColorPicker({
                flat: true,
                onChange: function (hsb, hex, rgb) {
                    jQuery('#colorpicker3').val('#' + hex);
                }
            });

            // Date Picker
            jQuery('#datepicker').datepicker();

            jQuery('#datepicker-inline').datepicker();

            jQuery('#datepicker-multiple').datepicker({
                numberOfMonths: 3,
                showButtonPanel: true
            });

            // Spinner
            var spinner = jQuery('#spinner').spinner();
            spinner.spinner('value', 0);

            // Input Masks
            jQuery("#date").mask("99/99/9999");
            jQuery("#phone").mask("(999) 999-9999");
            jQuery("#ssn").mask("999-99-9999");

            // Time Picker
            jQuery('#timepicker').timepicker({ defaultTIme: false });
            jQuery('#timepicker2').timepicker({ showMeridian: false });
            jQuery('#timepicker3').timepicker({ minuteStep: 15 });


        });

    </script>
}

RabbitHouse/Areas/Management/Views/ProductCategoryManage/Delete.cshtml
@model RabbitHouse.ViewModels.ProductCategoryManageDeleteViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutBracket.cshtml";
}

<div class="pageheader">
    <h2><i class="fa fa-edit"></i> ProductCategoryManage<span>进行商品分类管理</span></h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "SystemManage")">首页</a></li>
            <li>商品分类</li>
            <li><a href="@Url.Action("Index", "ProductCategoryManage")">商品分类列表</a></li>
            <li class="active">商品分类删除</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
    <div class="panel panel-default">
        @using (Html.BeginForm("Delete", "ProductCategoryManage", FormMethod.Post, htmlAttributes: new { @class = "" }))
        {
            <div class="panel-heading">
                <div class="panel-btns">
                    <a class="panel-close"></a>
                    <a class="minimize"></a>
                </div>
                <h4 class="panel-title">商品分类删除</h4>
                <p>您确定要删除以下商品分类吗？.</p>
                @Html.ValidationSummary()
            </div>
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            <div class="panel-body panel-body-nopadding">
                <div class="form-horizontal form-bordered">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-sm-3 control-label" })
                        <div class="col-sm-6 control-content">
                            @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-3 control-label" })
                        <div class="col-sm-6 control-content">
                            @Html.DisplayFor(model => model.Description, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "col-sm-3 control-label" })
                        <div class="col-sm-6 control-content">
                            @Html.DisplayFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                        </div>
                    </div>
                        
                </div>
            </div>

            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <button class="btn btn-danger" type="submit">删除</button>
                        <a class="btn btn-default" href="@Url.Action("Index")">返回</a>
                    </div>
                </div>
            </div>
        }
    </div>

</div><!-- contentpanel -->

RabbitHouse/Areas/Management/Views/ProductCategoryManage/Details.cshtml
@model RabbitHouse.ViewModels.ProductCategoryManageDetailsViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutBracket.cshtml";
}

<div class="pageheader">
    <h2><i class="fa fa-edit"></i> ProductCategoryManage<span>进行商品分类管理</span></h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","SystemManage")">首页</a></li>
            <li>商品分类</li>
            <li><a href="@Url.Action("Index","ProductCategoryManage")">商品分类列表</a></li>
            <li class="active">商品分类信息</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="panel-close"></a>
                <a class="minimize"></a>
            </div>
            <h4 class="panel-title">商品分类信息</h4>
            <p>您可以在此查看单个商品分类的信息.</p>
        </div>

        <div class="panel-body panel-body-nopadding">
            <div class="form-horizontal form-bordered">
                <div class="form-group">
                    @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.Id, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.Description, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>
      
            </div>
        </div>

        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <a class="btn btn-default" href="@Url.Action("Index","ProductCategoryManage")">返回</a>
                </div>
            </div>
        </div>
    </div>

</div><!-- contentpanel -->

RabbitHouse/Areas/Management/Views/ProductCategoryManage/Edit.cshtml
@model RabbitHouse.ViewModels.ProductCategoryManageEditViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutBracket.cshtml";
}

<div class="pageheader">
    <h2><i class="fa fa-edit"></i> ProductCategoryManage<span>进行商品分类管理</span></h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","SystemManage")">首页</a></li>
            <li>商品分类</li>
            <li><a href="@Url.Action("Index","ProductCategoryManage")">商品分类列表</a></li>
            <li class="active">编辑商品分类</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
    <div class="panel panel-default">
        @using (Html.BeginForm("Edit", "ProductCategoryManage", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal form-bordered", enctype = "multipart/form-data" }))
        {
            <div class="panel-heading">
                <div class="panel-btns">
                    <a class="panel-close"></a>
                    <a class="minimize"></a>
                </div>
                <h4 class="panel-title">商品分类信息</h4>
                <p>您可以在此查看并编辑单个商品分类的信息.</p>
            </div>

            @Html.AntiForgeryToken()
            @Html.ValidationSummary()
            @Html.HiddenFor(model => model.Id)

            <div class="panel-body panel-body-nopadding">

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6">
                        @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                        @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <button class="btn btn-primary" type="submit">保存</button>
                    </div>
                </div>
            </div>
        }
    </div>

</div><!-- contentpanel -->

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bracket/GeneralFormScript")

    <script>
        jQuery(document).ready(function () {
            //read and show img
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#post-img').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]);

                }
            }

            $("#CoverImg").change(function (e) {
                readURL(this);
                $('#post-img-path').val(e.target.files[0].name);
            });

            "use strict";

            // Tags Input
            jQuery('#tags').tagsInput({ width: 'auto' });

            // Select2
            jQuery(".select2").select2({
                width: '100%'
            });

            // Textarea Autogrow
            jQuery('#autoResizeTA').autogrow();

            // Color Picker
            if (jQuery('#colorpicker').length > 0) {
                jQuery('#colorSelector').ColorPicker({
                    onShow: function (colpkr) {
                        jQuery(colpkr).fadeIn(500);
                        return false;
                    },
                    onHide: function (colpkr) {
                        jQuery(colpkr).fadeOut(500);
                        return false;
                    },
                    onChange: function (hsb, hex, rgb) {
                        jQuery('#colorSelector span').css('backgroundColor', '#' + hex);
                        jQuery('#colorpicker').val('#' + hex);
                    }
                });
            }

            // Color Picker Flat Mode
            jQuery('#colorpickerholder').ColorPicker({
                flat: true,
                onChange: function (hsb, hex, rgb) {
                    jQuery('#colorpicker3').val('#' + hex);
                }
            });

            // Date Picker
            jQuery('#datepicker').datepicker();

            jQuery('#datepicker-inline').datepicker();

            jQuery('#datepicker-multiple').datepicker({
                numberOfMonths: 3,
                showButtonPanel: true
            });

            // Spinner
            var spinner = jQuery('#spinner').spinner();
            spinner.spinner('value', 0);

            // Input Masks
            jQuery("#date").mask("99/99/9999");
            jQuery("#phone").mask("(999) 999-9999");
            jQuery("#ssn").mask("999-99-9999");

            // Time Picker
            jQuery('#timepicker').timepicker({ defaultTIme: false });
            jQuery('#timepicker2').timepicker({ showMeridian: false });
            jQuery('#timepicker3').timepicker({ minuteStep: 15 });


        });
    </script>
}