RabbitHouse/Areas/Management/ViewModels/ProductManageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using RabbitHouse.Models;

namespace RabbitHouse.ViewModels
{
    public class ProductManageEditViewModel
    {
        [Display(Name="ID")]
        public int Id { get; set; }
        [Display(Name = "名称")]
        public string Name { get; set; }
        [Display(Name = "一句话描述")]
        public string ShortDescription { get; set; }
        [Display(Name = "描述文")]
        public string Description { get; set; }
        [Display(Name = "备注")]
        public string Remark { get; set; }
        [Display(Name = "封面图片Url")]
        public string CoverImgUrl { get; set; }
        [Display(Name = "封面图片")]
        public HttpPostedFileBase CoverImg { get; set; }

        public string UploadImgsIdString { get; set; }
        public string DeletedImgsFileNameString { get; set; }

        public IList<ProductImage> Imgs { get; set; }

        [Display(Name = "价格")]
        public decimal Price { get; set; }
        [Display(Name = "折扣")]
        public decimal? CurrentDiscount { get; set; }
        [Display(Name = "折扣开始时间")]
        public DateTime? DiscountStartTime { get; set; }
        [Display(Name = "折扣结束时间")]
        public DateTime? DiscountEndTime { get; set; }

        [Display(Name = "发布日期")]
        public DateTime PublishTime { get; set; }
        [Display(Name = "是否为时季商品")]
        public bool IsSeasonalProduct { get; set; }
        [Display(Name = "时季商品销售开始时间")]
        public DateTime? SaleStartTime { get; set; }
        [Display(Name = "时季商品销售结束时间")]
        public DateTime? SaleEndTime { get; set; }
        [Display(Name = "类别")]
        public int ProductCategoryForProduct { get; set; }
        [Display(Name="属性")]
        public IList<int> ProductPropertyForProduct { get; set; }

        public IList<ProductCategory> ProductCategories { get; set; }
        public IList<ProductProperty> ProductProperties { get; set; }
    }

    public class ProductManageCreateViewModel
    {
        [Display(Name = "名称")]
        public string Name { get; set; }
        [Display(Name = "一句话描述")]
        public string ShortDescription { get; set; }
        [Display(Name = "描述文")]
        public string Description { get; set; }
        [Display(Name = "备注")]
        public string Remark { get; set; }
        [Display(Name = "封面图片Url")]
        public string CoverImgUrl { get; set; }
        [Display(Name = "封面图片")]
        public HttpPostedFileBase CoverImg { get; set; }
        public string UploadImgsIdString { get; set; }


        [Display(Name = "价格")]
        public decimal Price { get; set; }
        [Display(Name = "折扣")]
        public decimal? CurrentDiscount { get; set; }
        [Display(Name = "折扣开始时间")]
        public DateTime? DiscountStartTime { get; set; }
        [Display(Name = "折扣结束时间")]
        public DateTime? DiscountEndTime { get; set; }

        [Display(Name = "发布日期")]
        public DateTime PublishTime { get; set; }
        [Display(Name = "是否为时季商品")]
        public bool IsSeasonalProduct { get; set; }
        [Display(Name = "时季商品销售开始时间")]
        public DateTime? SaleStartTime { get; set; }
        [Display(Name = "时季商品销售结束时间")]
        public DateTime? SaleEndTime { get; set; }
        [Display(Name = "类别")]
        public int ProductCategoryForProduct { get; set; }
        [Display(Name = "属性")]
        public IList<int> ProductPropertyForProduct { get; set; }

        public IList<ProductCategory> ProductCategories { get; set; }
        public IList<ProductProperty> ProductProperties { get; set; }
    }
    public class ProductManageDetailsViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }
        [Display(Name = "名称")]
        public string Name { get; set; }
        [Display(Name = "一句话描述")]
        public string ShortDescription { get; set; }
        [Display(Name = "描述文")]
        public string Description { get; set; }
        [Display(Name = "备注")]
        public string Remark { get; set; }
        [Display(Name = "封面图片Url")]
        public string CoverImgUrl { get; set; }
        [Display(Name = "内容图片")]
        public IList<ProductImage> Imgs { get; set; }

        [Display(Name = "价格")]
        public decimal Price { get; set; }
        [Display(Name = "折扣")]
        public decimal? CurrentDiscount { get; set; }
        [Display(Name = "折扣开始时间")]
        public DateTime? DiscountStartTime { get; set; }
        [Display(Name = "折扣结束时间")]
        public DateTime? DiscountEndTime { get; set; }

        [Display(Name = "发布日期")]
        public DateTime PublishTime { get; set; }
        [Display(Name = "是否为时季商品")]
        public bool IsSeasonalProduct { get; set; }
        [Display(Name = "时季商品销售开始时间")]
        public DateTime? SaleStartTime { get; set; }
        [Display(Name = "时季商品销售结束时间")]
        public DateTime? SaleEndTime { get; set; }
        [Display(Name = "类别")]
        public ProductCategory Category { get; set; }
        [Display(Name = "属性")]
        public IList<ProductProperty> Properties { get; set; }
    }

    public class ProductManageDeleteViewModel
    {
        [Display(Name = "ID")]
        public int Id { get; set; }
        [Display(Name = "名称")]
        public string Name { get; set; }
        [Display(Name = "一句话描述")]
        public string ShortDescription { get; set; }
        [Display(Name = "描述文")]
        public string Description { get; set; }
        [Display(Name = "备注")]
        public string Remark { get; set; }
        [Display(Name = "封面图片Url")]
        public string CoverImgUrl { get; set; }
        [Display(Name = "内容图片")]
        public IList<ProductImage> Imgs { get; set; }

        [Display(Name = "价格")]
        public decimal Price { get; set; }
        [Display(Name = "折扣")]
        public decimal? CurrentDiscount { get; set; }
        [Display(Name = "折扣开始时间")]
        public DateTime? DiscountStartTime { get; set; }
        [Display(Name = "折扣结束时间")]
        public DateTime? DiscountEndTime { get; set; }

        [Display(Name = "发布日期")]
        public DateTime PublishTime { get; set; }
        [Display(Name = "是否为时季商品")]
        public bool IsSeasonalProduct { get; set; }
        [Display(Name = "时季商品销售开始时间")]
        public DateTime? SaleStartTime { get; set; }
        [Display(Name = "时季商品销售结束时间")]
        public DateTime? SaleEndTime { get; set; }
        [Display(Name = "类别")]
        public ProductCategory Category { get; set; }
        [Display(Name = "属性")]
        public IList<ProductProperty> Properties { get; set; }
    }
}

RabbitHouse/Areas/Management/Controllers/ProductManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RabbitHouse.Models;
using RabbitHouse.ViewModels;
using System.IO;
using RabbitHouse.ExternalClasses;

namespace RabbitHouse.Areas.Management.Controllers
{
    public class ProductManageController : Controller
    {
        private RabbitHouseDbContext db = new RabbitHouseDbContext();

        // GET: ProductManage
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: ProductManage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            var vm = new ProductManageDetailsViewModel
            {
                Id = product.Id,
                Name = product.Name,
                ShortDescription = product.ShortDescription,
                Remark = product.Remark,
                CoverImgUrl = product.CoverImgUrl,
                Imgs = product.Imgs,

                Price = product.Price,
                CurrentDiscount = product.CurrentDiscount,
                DiscountStartTime = product.DiscountStartTime,
                DiscountEndTime = product.DiscountEndTime,

                PublishTime = product.PublishTime,

                IsSeasonalProduct = product.IsSeasonalProduct,
                SaleStartTime = product.SaleStartTime,
                SaleEndTime = product.SaleEndTime,

                Category = product.Category,
                Properties = product.Properties
            };
            return View(vm);
        }

        // GET: ProductManage/Create
        public ActionResult Create()
        {
            var vm = new ProductManageCreateViewModel
            {
                PublishTime=DateTime.Now,
                ProductCategories = db.ProductCategories.ToList(),
                ProductProperties = db.ProductProperties.ToList()
            };
            return View(vm);
        }

        // POST: ProductManage/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductManageCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                //find properties in db
                var productPropertis = db.ProductProperties.Where(p => model.ProductPropertyForProduct.Contains(p.Id)).ToList();

                var product = new Product
                {
                    Name = model.Name,
                    ShortDescription = model.ShortDescription,
                    Remark = model.Remark,

                    Price = model.Price,
                    CurrentDiscount = model.CurrentDiscount,
                    DiscountStartTime = model.DiscountStartTime,
                    DiscountEndTime = model.DiscountEndTime,

                    PublishTime = model.PublishTime,

                    IsSeasonalProduct = model.IsSeasonalProduct,
                    SaleStartTime = model.SaleStartTime,
                    SaleEndTime = model.SaleEndTime,

                    CategoryId = model.ProductCategoryForProduct,
                    Properties = productPropertis
                };

                //store in db and get the id
                db.Products.Add(product);
                db.SaveChanges();

                if (model.CoverImg != null)
                {
                    var uploadedFile = new UploadedFile(model.CoverImg);
                    var coverImgName=uploadedFile.SaveAsWithGuid(Server.MapPath("~/ImgRepository/ProductImgs/" + product.Id));

                    var pathRel = Url.Content("~/ImgRepository/ProductImgs/" + product.Id + "/" + coverImgName);
                    product.CoverImgUrl = pathRel;

                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                }

                //update ProductId for each uploaded ProductImg
                if (!string.IsNullOrEmpty(model.UploadImgsIdString))
                {
                    var uploadedImgsIdArray = model.UploadImgsIdString.Split(',');
                    foreach (var item in uploadedImgsIdArray)
                    {
                        if (!string.IsNullOrEmpty(item))
                        {
                            var productImg = db.ProductImages.Where(pImage => pImage.Id.ToString() == item).Single();
                            //move to product's folder
                            var imgName = UploadedFile.UploadedFileMoveTo(productImg.Url, Path.Combine(Server.MapPath("~/ImgRepository/ProductImgs/" + product.Id), (new FileInfo(productImg.Url)).Name));

                            var newPathRel= Url.Content("~/ImgRepository/ProductImgs/" + product.Id + "/" + imgName);
                            productImg.Url = newPathRel;
                            productImg.ProductId = product.Id;

                            db.SaveChanges();
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            model.ProductCategories = db.ProductCategories.ToList();
            model.ProductProperties = db.ProductProperties.ToList();
            return View(model);
        }

        // GET: ProductManage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            //ViewBag.CategoryId = new SelectList(db.ProductCategories, "Id", "Name", product.CategoryId);

            var productCategories = db.ProductCategories.ToList();

            var productProperies = db.ProductProperties.ToList();
            var productPropertyIdList = new List<int>();
            foreach(var item in product.Properties)
            {
                productPropertyIdList.Add(item.Id);
            }
            var vm = new ProductManageEditViewModel {
                Id = product.Id,
                Name = product.Name,
                ShortDescription=product.ShortDescription,
                Description=product.Description,
                Remark=product.Remark,
                CoverImgUrl=product.CoverImgUrl,

                Price=product.Price,
                CurrentDiscount=product.CurrentDiscount,
                DiscountStartTime=product.DiscountStartTime,
                DiscountEndTime=product.DiscountEndTime,

                PublishTime=product.PublishTime,
                IsSeasonalProduct=product.IsSeasonalProduct,
                SaleStartTime=product.SaleStartTime,
                SaleEndTime=product.SaleEndTime,

                ProductCategoryForProduct = product.Category.Id,
                ProductCategories=productCategories,

                ProductPropertyForProduct=productPropertyIdList,
                ProductProperties=productProperies
            };

            return View(vm);
        }

        [HttpPost]
        public ActionResult UploadImgs()
        {
            bool isSavedSuccessfully = true;
            string errorMessage="";
            var uploadedIDList = new List<UploadedImageInfo>();
            try
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];

                    //Save file content goes here
                    if (file != null && file.ContentLength > 0)
                    {
                        var contentImgName = Guid.NewGuid().ToString() + "_" + file.FileName;
                        var pathAbs = Path.Combine(Server.MapPath("~/ImgRepository/ProductImgs/temp"), contentImgName);

                        Directory.CreateDirectory(Path.GetDirectoryName(pathAbs));
                        file.SaveAs(pathAbs);
                        //var pathRel = Url.Content("~/ImgRepository/ProductImgs/temp/" + contentImgName);

                        var productImg = new ProductImage
                        {
                            Name = file.FileName,
                            Url = pathAbs,
                            RecordTime=DateTime.Now,
                        };
                        db.ProductImages.Add(productImg);
                        db.SaveChanges();

                        uploadedIDList.Add(new UploadedImageInfo
                        {
                            Id=productImg.Id.ToString(),
                            FileName=productImg.Name
                        });
                    }

                }

            }
            catch (Exception ex)
            {
                isSavedSuccessfully = false;
                errorMessage = ex.Message;
            }

            if (isSavedSuccessfully)
            {
                return Json(new { Info=uploadedIDList },JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Message = "Error in saving file:"+ errorMessage });
            }
        }

        public ActionResult GetProductImgs(int id)
        {
            var imgs = db.ProductImages.Where(p => p.ProductId == id).ToList();

            var storedImgList = new List<StoredImageInfo>();
            foreach(var item in imgs)
            {
                var storedImg = new StoredImageInfo
                {
                    Id = item.Id.ToString(),
                    FileName = item.Name,
                    Url = item.Url

RabbitHouse/Areas/Management/Views/ProductManage/Delete.cshtml
@model RabbitHouse.ViewModels.ProductManageDeleteViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutBracket.cshtml";
}

<div class="pageheader">
    <h2><i class="fa fa-edit"></i> ProductManage<span>进行商品管理</span></h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "SystemManage")">首页</a></li>
            <li>商品</li>
            <li><a href="@Url.Action("Index", "ProductManage")">商品列表</a></li>
            <li class="active">商品删除</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
    <div class="panel panel-default">
        @using (Html.BeginForm("Delete", "ProductManage", FormMethod.Post, htmlAttributes: new { @class = "" }))
        {
        <div class="panel-heading">
            <div class="panel-btns">
                <a class="panel-close"></a>
                <a class="minimize"></a>
            </div>
            <h4 class="panel-title">商品删除</h4>
            <p>您确定要删除以下商品吗？.</p>
        </div>
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        @Html.HiddenFor(model => model.Id)
        <div class="panel-body panel-body-nopadding">
            <div class="form-horizontal form-bordered">
                <div class="form-group">
                    @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.Id, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.Category.Name, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.Remark, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CoverImgUrl, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        <div>
                            <img class="mb10" src="@Model.CoverImgUrl" alt="..." />
                        </div>

                        @Html.DisplayFor(model => model.CoverImgUrl, new { htmlAttributes = new { @id = "post-img-path", @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        ￥@Html.DisplayFor(model => model.Price, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CurrentDiscount, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.CurrentDiscount, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DiscountStartTime, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.DiscountStartTime, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DiscountEndTime, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.DiscountEndTime, new { htmlAttributes = new { @class = "form-control", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsSeasonalProduct, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-md-6">
                        <div class="checkbox block">
                            <label>
                                @Html.CheckBoxFor(model => model.IsSeasonalProduct, htmlAttributes: new { @class = "", @placeholder = "", @readonly = "readonly", @disabled = "" })
                                时季商品
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SaleStartTime, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.SaleStartTime, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SaleEndTime, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.SaleEndTime, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Properties, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @foreach (var prop in Model.Properties)
                        {
                            <img src="@prop.ImgUrl" />
                        }
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PublishTime, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.PublishTime, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @Html.DisplayFor(model => model.Description, new { htmlAttributes = new { @class = "", @placeholder = "" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Imgs, htmlAttributes: new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-6 control-content">
                        @foreach (var img in Model.Imgs)
                        {
                            <img src="@img.Url" />
                        }
                    </div>
                </div>
            </div>
        </div>

        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <button class="btn btn-danger" type="submit">删除</button>
                    <a class="btn btn-default" href="@Url.Action("Index")">返回</a>
                </div>
            </div>
        </div>
        }
    </div>

</div><!-- contentpanel -->

RabbitHouse/Areas/Management/Views/ProductManage/Index.cshtml
@model IEnumerable<RabbitHouse.Models.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutBracket.cshtml";
}


<div class="pageheader">
    <h2><i class="fa fa-edit"></i> ProductManage<span>进行商品管理</span></h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index","SystemManage")">首页</a></li>
            <li>商品</li>
            <li class="active">商品列表</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
    <div class="row">
        <div class="col-md-12">
            <h5 class="subtitle mb5">商品列表</h5>
            <p class="mb5">您可以在此查看并编辑商品信息.</p>
            <a class="btn btn-primary btn-xs mb10" href="@Url.Action("Create","ProductManage")">创建一个新的商品</a>
            <div class="table-responsive">
                <table class="table table-hidaction table-hover mb30">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>名称</th>
                            <th>价格</th>
                            <th>类别</th>
                            <th>发布日期</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>￥@item.Price</td>
                                <td>@item.Category.Name</td>
                                <td>@item.PublishTime</td>
                                <td class="table-action-hide">
                                    <a href="@Url.Action("Details","ProductManage",new { id=item.Id })">
                                        <i class="fa fa-file-text-o"></i>
                                    </a>
                                    <a href="@Url.Action("Edit","ProductManage",new { id=item.Id })">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <a href="@Url.Action("Delete","ProductManage",new { id=item.Id })">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div><!-- contentpanel -->

@section scripts{

    @Scripts.Render("~/bundles/bracket/TableScript")

    <script>
        jQuery(document).ready(function () {

            "use strict";

            jQuery('#table1').dataTable();

            jQuery('#table2').dataTable({
                "sPaginationType": "full_numbers"
            });

            // Select2
            jQuery('select').select2({
                minimumResultsForSearch: -1
            });

            jQuery('select').removeClass('form-control');

            // Delete row in a table
            jQuery('.delete-row').click(function () {
                var c = confirm("Continue delete?");
                if (c)
                    jQuery(this).closest('tr').fadeOut(function () {
                        jQuery(this).remove();
                    });

                return false;
            });

            // Show aciton upon row hover
            jQuery('.table-hidaction tbody tr').hover(function () {
                jQuery(this).find('.table-action-hide a').animate({ opacity: 1 });
            }, function () {
                jQuery(this).find('.table-action-hide a').animate({ opacity: 0 });
            });


        });
    </script>
}